trigger:
- master

pool:
  name: kha333n
  demands:
   - agent.name -equals KHA333N 

steps:
- script: |
    cd C:\WorkingDirectoryAZAgent\
    git clone $(repo)
    cd laravelLearningProject
    php artisian serve
  displayName: 'Run a build script'