trigger:
- master

pool:
  name: kha333n
  demands:
   - agent.name -equals KHA333N 

steps:
- script: |
    cd C:\Users\Usman Khan\IdeaProjects\laravelLearningProject>
    php artisan serve
  displayName: 'Run a Start Stcript'

- script: |
    stat http://localhost:8000
  displayName: 'Open Site'